image: node:16

stages:
  - Formatting
  - Linting
  - Testing

prettier:
  stage: Formatting
  retry: 1
  script:
    - npm ci
    - npm run prettier

eslint:
  stage: Linting
  retry: 1
  script:
    - npm ci
    - npm run lint

jest:
  stage: Testing
  retry: 1
  script:
    - npm ci
    - npm run test
